name: misskey_dart
description: Misskey API wrapper
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  dotenv: ^4.1.0
  freezed: ^3.0.0
  json_serializable: ^6.6.1
  lints: ^5.1.1
  test: ^1.25.1
  uuid: ^4.5.1
dependencies:
  collection: ^1.16.0
  dio: ^5.1.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.0
  path: ^1.8.2
  web_socket_channel: ^3.0.3